[theme]
base = "dark"
primaryColor = "#9D1939"
backgroundColor = "#060E1A"
secondaryBackgroundColor = "#0E1A2C"
textColor = "#F2F2F0"
font = "sans serif"

[server]
headless = true
runOnSave = true

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
showErrorDetails = true
