[theme]
base = "dark"
primaryColor = "#9D1939"
backgroundColor = "#0A0A0B"
secondaryBackgroundColor = "#13131A"
textColor = "#F2F2F0"
font = "sans serif"

[server]
headless = true
runOnSave = true

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
showErrorDetails = true
